[info]
relay_url = "wss://localhost:8081"
name = "nostr_relay"
description = "Nostr Relay"

[database]
engine = "sqlite"
data_directory = "/home/dev/.nostr_relay/db"

[network]
address = "0.0.0.0"
port = 8081

[options]
# Reject events that have timestamps greater than this many seconds in
# the future.
reject_future_seconds = 1800 # 30 minutes
